### ISSUE TITLE
Please change bugtracker link

### ISSUE THREAD

**Issue by pcav** [ale-cristofori/geotweet#1]
It currently points to the repo, not to the issues page.
Thanks.

**Comment by ale-cristofori** [comment]
https://github.com/ale-cristofori/geotweet/commit/35ebdd31a8570f49efb0b28522bc6b8b03583fc9
changed the metadata.txt to include right issue tracker page @pcav I will re-upload the plugin again

**Comment by pcav** [comment]
Published, thanks @ale-cristofori : coming to the upcoming QGIS-it hackfest in Padova?

**Comment by ale-cristofori** [comment]
Hi @pcav, I saw the programme, very interesting. Yes I’ll be there.

**Comment by pcav** [comment]
ottimo - ti consiglio di iscriverti al canale telegram, così smettiamo di abusare di questo ticket ;)

**Comment by ale-cristofori** [comment]
@pcav l’ho giusto installato perché non ce lo avevo. Mi puoi aggiungere tu? Il mio nickname è ale_cristofori

**Comment by pcav** [comment]
https://t.me/joinchat/B9-sGknpCj5xO8bap-v0YQ
